# Generated by Django 5.1.5 on 2025-03-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recettes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "verbose_name": "Ingredient",
                "verbose_name_plural": "Ingredients",
            },
        ),
    ]
