# Generated by Django 5.1.5 on 2025-05-08 17:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recettes", "0002_alter_ingredient_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valeur",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="La note minimale est 1"
                            ),
                            django.core.validators.MaxValueValidator(
                                5, message="La note maximale est 5"
                            ),
                        ]
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "recette",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="recettes.recette",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "unique_together": {("utilisateur", "recette")},
            },
        ),
    ]
