# Generated by Django 5.1.5 on 2025-05-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recettes", "0003_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("fichier", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.AlterField(
            model_name="categorie",
            name="image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="recette",
            name="image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="recetteingredient",
            unique_together={("recette", "ingredient")},
        ),
    ]
